spring:
  application:
    name: projetosaplicados
  datasource:
    url: jdbc:postgresql://localhost:5432/barbearia
    username: postgres
    password: 1412
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true